name: create docker image
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          # extended: true

      - name: Hugo Build
        run: |
          cd blog-site-tshst && hugo --minify -d ../docker-nginx-blog/html/

      - name: Docker Build
        uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            repository: tshst/blog
            path: ./docker-nginx-blog
            tag_with_ref: true
            tag_with_sha: true
